### ISSUE TITLE
Live chat wil not start

### ISSUE THREAD

**Issue by superboys2017** [php-kchat/kchat#4]
i cant start a live chat it wil sta on the sine in http://prntscr.com/r7ncjd

**Comment by superboys2017** [comment]
[25-Feb-2020 23:20:33 Europe/Berlin] PHP Notice:  Undefined index: group_id in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 181
[25-Feb-2020 23:20:33 Europe/Berlin] PHP Notice:  Undefined index: id in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 230
[25-Feb-2020 23:20:33 Europe/Berlin] PHP Notice:  Undefined index: id in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 232
[25-Feb-2020 23:20:38 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1615 Prepared statement needs to be re-prepared in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php:396
Stack trace:
#0 /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php(396): PDOStatement->execute(Array)
#1 /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php(65): KChat->getSupportid('4')
#2 /home/nyo/domains/powernode.be/public_html/staff/box/core/kchat.php(159): KChat->start(Array)
#3 /home/nyo/domains/powernode.be/public_html/staff/box/kchat.php(18): require_once('/home/nyo/domai...')
#4 {main}
  thrown in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 396
[25-Feb-2020 23:20:38 Europe/Berlin] PHP Notice:  Undefined index: group_id in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 181
[25-Feb-2020 23:20:38 Europe/Berlin] PHP Notice:  Undefined index: id in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 221
[25-Feb-2020 23:20:41 Europe/Berlin] PHP Notice:  Undefined index: group_id in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 181
[25-Feb-2020 23:20:41 Europe/Berlin] PHP Notice:  Undefined index: id in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 230
[25-Feb-2020 23:20:41 Europe/Berlin] PHP Notice:  Undefined index: id in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 232
[25-Feb-2020 23:20:44 Europe/Berlin] PHP Notice:  Undefined index: group_id in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 181
[25-Feb-2020 23:20:44 Europe/Berlin] PHP Notice:  Undefined index: id in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 230
[25-Feb-2020 23:20:44 Europe/Berlin] PHP Notice:  Undefined index: id in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 232
[25-Feb-2020 23:20:47 Europe/Berlin] PHP Notice:  Undefined index: group_id in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 181
[25-Feb-2020 23:20:47 Europe/Berlin] PHP Notice:  Undefined index: id in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 230
[25-Feb-2020 23:20:47 Europe/Berlin] PHP Notice:  Undefined index: id in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 232


this my error is you need it

**Comment by GaneshKandu** [comment]
Hi,

I am not able to reproduce this error.
can you please explain steps how did you get this error ?

**Comment by superboys2017** [comment]
I downloaded the file and i set it on my site hosting I have all mysql data and I tried and got this error I had prefix removed because I don't know it and it will not work @GaneshKandu

**Comment by GaneshKandu** [comment]
set ``ATTR_EMULATE_PREPARES`` to true

ie. 
```php
			$opt = array(
				PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
				PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
				PDO::ATTR_EMULATE_PREPARES   => true,
				PDO::MYSQL_ATTR_FOUND_ROWS => TRUE
			);
```
in ``box\core\sandesh.php`` ~ line no 17

see if works

**Comment by superboys2017** [comment]
[27-Feb-2020 20:09:36 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nyo_staff.kckt_guest' doesn't exist in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php:25
Stack trace:
#0 /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php(25): PDOStatement->execute(Array)
#1 /home/nyo/domains/powernode.be/public_html/staff/box/core/kchat.php(147): KChat->__construct(Array)
#2 /home/nyo/domains/powernode.be/public_html/staff/box/kchat.php(18): require_once('/home/nyo/domai...')
#3 {main}
  thrown in /home/nyo/domains/powernode.be/public_html/staff/box/core/sandesh.php on line 25
 



i get now this error

**Comment by GaneshKandu** [comment]
Hi,

Look like your database not installed successfully , ' guest' is missing
try reinstalling kchat
https://github.com/php-kchat/kchat/archive/master.zip

and set ATTR_EMULATE_PREPARES to true

Regards

Ganesh Kandu

**Comment by superboys2017** [comment]
[15-Mar-2020 18:33:41 Europe/Amsterdam] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1140 In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'nyo_werk.PN_msgs.sender_id'; this is incompatible with sql_mode=only_full_group_by in /home/nyo/domains/powernode.be/public_html/livechat/box/core/sandesh.php:396
Stack trace:
#0 /home/nyo/domains/powernode.be/public_html/livechat/box/core/sandesh.php(396): PDOStatement->execute(Array)
#1 /home/nyo/domains/powernode.be/public_html/livechat/box/core/sandesh.php(65): KChat->getSupportid('1')
#2 /home/nyo/domains/powernode.be/public_html/livechat/box/core/kchat.php(159): KChat->start(Array)
#3 /home/nyo/domains/powernode.be/public_html/livechat/box/kchat.php(18): require_once('/home/nyo/domai...')
#4 {main}
  thrown in /home/nyo/domains/powernode.be/public_html/livechat/box/core/sandesh.php on line 396
[15-Mar-2020 18:33:42 Europe/Amsterdam] PHP Notice:  Undefined index: group_id in /home/nyo/domains/powernode.be/public_html/livechat/box/core/sandesh.php on line 181
[15-Mar-2020 18:33:42 Europe/Amsterdam] PHP Notice:  Undefined index: id in /home/nyo/domains/powernode.be/public_html/livechat/box/core/sandesh.php on line 221
[15-Mar-2020 18:33:45 Europe/Amsterdam] PHP Notice:  Undefined index: group_id in /home/nyo/domains/powernode.be/public_html/livechat/box/core/sandesh.php on line 181
[15-Mar-2020 18:33:45 Europe/Amsterdam] PHP Notice:  Undefined index: id in /home/nyo/domains/powernode.be/public_html/livechat/box/core/sandesh.php on line 230
[15-Mar-2020 18:33:45 Europe/Amsterdam] PHP Notice:  Undefined index: id in /home/nyo/domains/powernode.be/public_html/livechat/box/core/sandesh.php on line 232
[15-Mar-2020 18:33:48 Europe/Amsterdam] PHP Notice:  Undefined index: group_id in /home/nyo/domains/powernode.be/public_html/livechat/box/core/sandesh.php on line 181
[15-Mar-2020 18:33:48 Europe/Amsterdam] PHP Notice:  Undefined index: id in /home/nyo/domains/powernode.be/public_html/livechat/box/core/sandesh.php on line 230
[15-Mar-2020 18:33:48 Europe/Amsterdam] PHP Notice:  Undefined index: id in /home/nyo/domains/powernode.be/public_html/livechat/box/core/sandesh.php on line 232


i get this sorry i dont have see you message

**Comment by GaneshKandu** [comment]
Hi,

you using mysql 5.7 i think.
```mysql
SET SESSION sql_mode = sys.list_add(@@session.sql_mode, 'ONLY_FULL_GROUP_BY');
```
run this query in mysql it will allow not-so-great queries
let me know if works.

Thanks

**Comment by superboys2017** [comment]
![image](https://user-images.githubusercontent.com/40305210/76743286-afb48f00-6772-11ea-84f8-ef76e82dc474.png)
i get now this error

**Comment by GaneshKandu** [comment]
Run ```composer update```
Tested on Mysql 8.0
found same error resolved now

**Comment by superboys2017** [comment]
i cant do that commend it is directadmin an i cant in the vps/dedi

**Comment by GaneshKandu** [comment]
Download and overwrite all file and folders on your install

**Comment by superboys2017** [comment]
it wil work thanks
